image: gitpod/workspace-postgres
tasks:
  - name: Build & Serve Slides
    command: npm install && npm start
ports:
  - port: 5432
    onOpen: ignore
    visibility: private
vscode:
  extensions:
    - marp-team.marp-vscode