image: gitpod/workspace-postgres
tasks:
  - name: Install Google Chrome
    command: |
      sudo ./init.sh
      npm install && npm start
ports:
  - port: 5432
    onOpen: ignore
    visibility: private
vscode:
  extensions:
    - marp-team.marp-vscode